name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Cache bitcoind
        id: cache-bitcoind
        uses: actions/cache@v5
        with:
          path: bitcoin-31.0
          key: ${{ runner.os }}-bitcoind
      - name: Download bitcoind
        if: steps.cache-bitcoind.outputs.cache-hit != 'true'
        run: |
          wget -q https://bitcoincore.org/bin/bitcoin-core-31.0/bitcoin-31.0-x86_64-linux-gnu.tar.gz
          tar xzf bitcoin-31.0-x86_64-linux-gnu.tar.gz
      - name: Set BITCOIND_EXE env
        run: echo "BITCOIND_EXE=$PWD/bitcoin-31.0/bin/bitcoind" >> $GITHUB_ENV
      - name: Check fmt
        run: cargo fmt --all --check
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
